apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-amazon-app
  labels:
    app: java-amazon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-amazon-app
  template:
    metadata:
      labels:
        app: java-amazon-app
    spec:
      containers:
      - name: java-amazon-app
        image: reka83/amazon-testng:latest
        ports:
        - containerPort: 8080
